version: '3'

services:
  web:
    build: ./docker-nginx
    ports:
        - 80:80
    depends_on:
        - app
    volumes:
        - ./:/var/www/html
        - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app

  app:
    build: ./docker-php
    depends_on:
        - db
    links:
        - db
    volumes:
        - ./docker-php/html/:/var/www/html

  db:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: dbpass

  bpf:
    image: motikan2010/bcc-docker
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    volumes:
        - /lib/modules:/lib/modules:ro
        - /usr/src:/usr/src:ro
        - /etc/localtime:/etc/localtime:ro
        - /sys/fs/bpf:/sys/fs/bpf
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/run/docker/netns:/var/run/docker/netns:rshared
        - ./docker-bpf/script:/root/script
    working_dir: /usr/share/bcc/tools
    tty: true
